In [1]:
print ('Hello Py!')

Hello Py!


In [2]:
i = 101

In [3]:
type(i)

int

In [4]:
f = 101.99 #float

In [5]:
type(f)

float

In [6]:
b = True #boolean variable, that is, TRUE and FALSE

In [7]:
s= "A string!"

In [8]:
print(s)

A string!


In [9]:
xx = 100+1
print(xx)
yy = 'i'+'feel'
print(yy)

101
ifeel


In [10]:
#python list
li = [7, 9, 5]

In [11]:
print(li);
print (li[0], li[1], li[2]); # elements of list can be accessed with
#index placed inside square brackets; index starts from 0.

[7, 9, 5]
7 9 5


In [12]:
print(li[-1], li[-2], li[-3]) 
# elements from the end of list

5 9 7


In [13]:
#loop though list
for i in li:
    print (i)
#Note: the indentation equivalent to tab spacing before the print command.

7
9
5


In [14]:
li2 = [li, li*2]
print(li2)
type(li2)

[[7, 9, 5], [7, 9, 5, 7, 9, 5]]


list

In [15]:
#  List slicing: to select multiple elements from a list 
#  li[start_index, end_index] means slicing begins at index 'start_index', and ends at index 
# 'end_index-1'
list1 = [2, 4, 'a', 8, 'b', 10]
list1[2:5]

['a', 8, 'b']

In [16]:
di = {'i':1, 'j':2.3, 'k':'dictionary'}  #dictionary

In [17]:
print(di)

{'i': 1, 'j': 2.3, 'k': 'dictionary'}


In [18]:
print(di['i'])

1


In [19]:
print(di['j'])

2.3


In [20]:
n = None #python's NULL type

In [21]:
type(n)

NoneType

In [22]:
print("Value of f is %.3f. Value of i is %d."% (f, i)) #string print out

Value of f is 101.990. Value of i is 5.


In [23]:
if i < 0:
    print("Negative value!")
elif i == 0:
    print("i is just 0.")
else:
    print("i is positive!")

i is positive!


In [24]:
counter = 6
while counter < 10:
    print(counter)
    counter += 1

6
7
8
9


In [25]:
hypotenuse = lambda x, y: x*x + y*y

In [26]:
print(hypotenuse(5, 1))

26


In [27]:
# Below is a list of ['name of fruit', cost of 1 fruit] 
shop = ['apple', 50, 'orange', 30, 'banana', 15, 'mango', 45]
print(shop)

# replace ['banana', 15] in shopping list with ['cucumber', 5]
shop[2:4] = ['cucumber', 5]
print(shop)

total_cost_shop = shop[1] + shop[3] + shop[5]
print("Total cost of shopping list = Rs. %f"% total_cost_shop)

['apple', 50, 'orange', 30, 'banana', 15, 'mango', 45]
['apple', 50, 'cucumber', 5, 'banana', 15, 'mango', 45]
Total cost of shopping list = Rs. 70.000000


In [28]:
#Extend a list
newshop = shop + ['avocado', '90']
print(newshop)

['apple', 50, 'cucumber', 5, 'banana', 15, 'mango', 45, 'avocado', '90']


In [29]:
#Delete elements from a list
del(newshop[-1])
del(newshop[-1])
print(newshop)

['apple', 50, 'cucumber', 5, 'banana', 15, 'mango', 45]


In [30]:
a = ['x', 'y', 'z']
print(a)
b = a #The address of variable a in the computer's memory is copied to another variable b. 
#But, both a and b now point to the same memory location.

b[2] = 1
print(a)
print(b)
#if b is changed, a is changed as well.

['x', 'y', 'z']
['x', 'y', 1]
['x', 'y', 1]


In [31]:
a = ['x', 'y', 'z']
print(a)
b = a[:] # The values 'x', 'y', 'z' stored in the variable a is copied to a new variable b.
# Equivalent way of writing this line is: b = list(a) 
b[2] = 1
print(a)
print(b)

['x', 'y', 'z']
['x', 'y', 'z']
['x', 'y', 1]


In [32]:
#List of Lists
m = [['a', 'b', 'c'],
     ['d', 'e', 'f'],
     ['g', 'h', 'i']]
print(m[1][0])          # row index = 1, column index = 0
print(m[1][:2])         # list subsetting

d
['d', 'e']


In [33]:
# User-defined functions in Python are constructed using def keyword
def mysquare(x):
    z = x*x           # Indent all the lines of code that are inside the function.
    return z

#Call the function
i = 5
print(mysquare(i));

25


In [34]:
#built-in functions in Python
round(10.123456)

10

In [35]:
round(10.123456, 3)

10.123

In [36]:
help (round)

Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.



In [37]:
max([109, 1, -1, -100, 5]) # maximum value of a list

109

In [38]:
len([109, 1, -1, -100, 5]) #length of a list

5

In [39]:
help (complex)

Help on class complex in module builtins:

class complex(object)
 |  complex(real[, imag]) -> complex number
 |  
 |  Create a complex number from a real part and an optional imaginary part.
 |  This is equivalent to (real + imag*1j) where imag defaults to 0.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(...)
 |      complex.__format__() -> str
 |      
 |      Convert to a string according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(...)
 |  
 |  __gt__(self, va

In [40]:
#In Python, data is represented as 'Object'.
#A function belonging to an object is called 'method'. 
#Depending on the type of object, predefined methods are associated with objects. 
shop = ['apple', 50, 'orange', 30, 'banana', 15, 'mango', 45]
shop.index('apple')         #variable 'shop' is an object of type 'List'. 
#'index()' is an example of a method  

0

In [41]:
shop.index('banana')   
#call method 'index()' on object 'shop'
shop.count('mango')    #call method 'count()' on object 'shop'

1

In [42]:
name = 'khushhal'
print(name)

khushhal


In [43]:
name.capitalize() #call method 'capitalize()' on name

'Khushhal'

In [44]:
name.replace('a','z') #call method 'replace()' on name

'khushhzl'

In [45]:
print([1, 2, 3, 4]*2)
#in this example the math operation on a list of integers does not work

[1, 2, 3, 4, 1, 2, 3, 4]


In [46]:
import numpy as np
print (np.array([1, 2, 3, 4])*2)

[2 4 6 8]


In [47]:
nu = np.array([20, 30, 40, 50])
denom = np.array([1, 2, 3, 4,])
print(nu/denom**2)

[20.          7.5         4.44444444  3.125     ]


In [48]:
#A 2 dimensional array.
ar = np.array([[1, 2, 3], [4, 5, 6]])
print(ar)
print(type(ar))
print(ar.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [49]:
print(ar[0,0], ar[0,1], ar[0,2])
ar[0,1] = 9 #re-assign an element in the row=0, column=1 of the array 
print(ar)

1 2 3
[[1 9 3]
 [4 5 6]]


In [50]:
import numpy as np
#Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:2, 1:3]
print (b)

[[2 3]
 [6 7]]


In [51]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   
b[0,0]=23
# b[0, 0] is the same piece of data as a[0, 1]
print(a[0,1])

2
23


In [52]:
import numpy as np
#create the following ,rank 2 array with shape (3,4)
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

#Two ways of accessing the data in the middle row of the array.
#Mixiing integer indexing with slices yields an array of lower rank,
#while using only slices yields an array of the same rank as the orginal array:

row_r1 = a[1, :] # Rank 1 view of the second row of a
row_r2 = a[1:2, :] # Rank 2 view of the second row of a
print (row_r1, row_r1.shape)
print (row_r2, row_r2.shape)

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print (col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [53]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print (a[[0,1,2],[0,1,0]])

# The above eg. of integer array indexing is equivalent to this:
print (np.array([a[0,0], a[1,1], a[2,0]]))

# When using integer array indexing, you can reuse the same
# elements from the source array:
print (a[[0,0], [1,1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0,1], a[0,1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [58]:
import numpy as np
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print (a,"\n")  
# prints "array([[ 1,  2,  3],
#                [ 4,  5,  6],
#                [ 7,  8,  9],
#                [10, 11, 12]])"
# Create an array of indices

b = np.array([0,2,0,1])

print(np.arange(4),"\n")
# Select one element from each row of a using the indices in b
print(a[np.arange(4), b],"\n")  

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a,"\n")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[0 1 2 3] 

[ 1  6  7 11] 

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]] 



In [55]:
import numpy as np

a = np.array([[1,2], [3,4], [5,6]])

bool_idx = (a > 4)   
# The condition in bracket filters out the elements of array 'a' that 
# are larger than 4;

print (bool_idx)      
# Prints a Boolean array "[[False False]
#                         [ True  True]
#                         [ True  True]]"

print(a[bool_idx])  # Prints "[5 6]"
print(a[a >4])     # Prints "[5 6]"

[[False False]
 [False False]
 [ True  True]]
[5 6]
[5 6]


In [59]:
x = np.array([2.0, -1.0, -3.0, 5])
x[x<0] += 7
print(x)

[ 9. -1. -3. 12.]
